export {default as Benefits} from './benefits/Benefits'
export {default as Contact} from './contact/Contact'
export {default as Guide} from './guide/Guide'
export {default as Intro} from './intro/Intro'
export {default as Footer} from './footer/Footer'
export {default as Upload} from './upload/Upload'